# Generated by Django 5.2.4 on 2025-08-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_alter_user_username'),
    ]

    operations = [
        # This migration is empty because the staff_details table already exists
        # and Django will use it due to the db_table = 'staff_details' setting
        # in the StaffDetails model
    ]
