# Generated by Django 5.2.4 on 2025-08-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_use_existing_staff_details_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        DO $$
                        BEGIN
                          IF to_regclass('public.processor_staffdetails') IS NOT NULL
                             AND to_regclass('public.staff_details') IS NULL THEN
                            EXECUTE 'ALTER TABLE processor_staffdetails RENAME TO staff_details';
                          END IF;
                        END$$;
                        """
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='staffdetails',
                    table='staff_details',
                ),
            ],
        ),
    ]
