# Generated by Django 5.2.4 on 2025-08-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_use_existing_staff_details_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffdetails',
            table='staff_details',
        ),
    ]
