services:
  web:
    build: .
    container_name: nac-attendance-web
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - /admin-app/staticfiles:/app/staticfiles
      - /admin-app/media:/app/media

  db:
    image: postgres:15
    container_name: nac-attendance-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:


